week4 assesment complete
learn-academy-2021-delta/week-4-assessment-HackCoder77 pull request #1
Opened 2021-10-04 15:34 UTC by HackCoder77

Assessment completed!

2021-10-05 18:01 UTC, WalkerTexas-coder requested changes
Requiring rewrite to researched interview answer #3

2021-10-05 18:01 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +remove(colors1)
The logic in this function is good, but I can see this wont make the test pass which is the goal here. Keep that in mind when you're at work if you are ever doing anything dealing with QA.

2021-10-05 18:01 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +//realized i don't need a blank array, i just put the numbers it returned into an array
Well done!

2021-10-05 18:01 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +noDupes(testArray1, testArray2)
great work! I would like to see you solution to the stretch challenge though. I bet it would be real clean.

2021-10-05 18:01 UTC, WalkerTexas-coder commented on code_challenges.rb
> +end
This last answer is what we're looking for when we say "Create a method" the logic you have for the other problems won't be super helpful for test cases that weren't explicitly provided. Whenever we are coding we are coding for the widest variety of test cases possible. Thats what we call making our code "robust."

2021-10-05 18:01 UTC, WalkerTexas-coder commented on interview-questions.md
> +When a user presses a key[2]
Excellent!

2021-10-05 18:01 UTC, WalkerTexas-coder commented on interview-questions.md
> +Object-oriented programming (OOP) is a computer programming model that organizes software design around data, or objects, rather than functions and logic. An object can be defined as a data field tha
Hey if I google OOP then I get this answer! Cool! Sending it back to you for a re write.

2021-10-06 16:48 UTC, HackCoder77 commented on code_challenges.rb
> +end
Could you expand on exactly what you mean here? I don't think im following exactly what you are trying to tell me here.....

2021-10-06 16:49 UTC, merged